name: Generate Activity Graph

on:
  schedule:
    - cron: "23 2 * * *"  # Off-peak automated daily run (~7:53 AM IST)
  push:
    branches:
      - main              # Automatically updates whenever you push to main
  workflow_dispatch:      # Allows manual trigger anytime

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Isometric Calendar & Streaks
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Yash4305d-y
          template: classic
          base: ""
          filename: activity-graph.svg
          output_action: commit
          committer_branch: output
          config_timezone: Asia/Kolkata
          plugin_activity: no
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
