name: Generate Activity Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Tokyo Night Activity Graph
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Yash4305d-y
          template: classic
          base: ""
          filename: output/activity-graph.svg
          config_timezone: Asia/Kolkata
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_style: compact
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
